# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicecatalog', '0041_module_is_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('environment', models.CharField(choices=[('d', 'Development'), ('i', 'Integration'), ('q', 'Quality Assurance'), ('ct', 'Customer Test'), ('p', 'Production')], default=None, max_length=2)),
                ('customer_accesable', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('d', 'In development'), ('l', 'Live'), ('X', 'Deprecated')], default='l', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceConnectsInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_direction', models.CharField(choices=[('r', 'Read'), ('w', 'Write'), ('rw', 'Read/Write')], default='rw', max_length=2)),
                ('comment', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('is_online', models.NullBooleanField(default=None)),
                ('from_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_from_relation', to='instance_manager.Instance')),
                ('payment_methods', models.ManyToManyField(blank=True, default=None, to='servicecatalog.PaymentMethod')),
                ('to_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_to_relation', to='instance_manager.Instance')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='connected_to_instance',
            field=models.ManyToManyField(blank=True, default=None, related_name='instance_on_instance', through='instance_manager.InstanceConnectsInstance', to='instance_manager.Instance'),
        ),
        migrations.AddField(
            model_name='instance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance_manager.Location'),
        ),
        migrations.AddField(
            model_name='instance',
            name='maintained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintained_by', to='servicecatalog.Contact'),
        ),
        migrations.AddField(
            model_name='instance',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_of_module', to='servicecatalog.Module'),
        ),
        migrations.AlterUniqueTogether(
            name='instanceconnectsinstance',
            unique_together=set([('from_instance', 'to_instance', 'access_direction')]),
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together=set([('name', 'module', 'environment', 'location')]),
        ),
    ]
