# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0041_module_is_external'),
        ('instance_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceConnectsModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_direction', models.CharField(choices=[('r', 'Read'), ('w', 'Write'), ('rw', 'Read/Write')], default='rw', max_length=2)),
                ('comment', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('is_online', models.NullBooleanField(default=None)),
                ('from_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_instance_to_module_relation', to='instance_manager.Instance')),
                ('payment_methods', models.ManyToManyField(blank=True, default=None, to='servicecatalog.PaymentMethod')),
                ('to_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_module_from_instance_relation', to='servicecatalog.Module')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='connected_to_module',
            field=models.ManyToManyField(blank=True, default=None, related_name='instance_on_module', through='instance_manager.InstanceConnectsModule', to='servicecatalog.Module'),
        ),
        migrations.AlterUniqueTogether(
            name='instanceconnectsmodule',
            unique_together=set([('from_instance', 'to_module', 'access_direction')]),
        ),
    ]
