# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0041_module_is_external'),
        ('instance_manager', '0002_auto_20161002_1526'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instanceconnectsmodule',
            unique_together=set([('from_instance', 'to_module', 'access_direction', 'is_online')]),
        ),
    ]
