# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance_manager', '0005_auto_20161018_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='maintained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintained_by', to='contact_manager.Contact'),
        ),
    ]
