# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0009_contactoptions_human_string'),
        ('instance_manager', '0006_auto_20161020_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_manager.Contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='instance',
            name='maintained_by',
        ),
        migrations.AddField(
            model_name='instancecontact',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance_manager.Instance'),
        ),
        migrations.AddField(
            model_name='instancecontact',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_manager.ContactRole'),
        ),
        migrations.AlterUniqueTogether(
            name='instancecontact',
            unique_together=set([('parent', 'contact', 'role')]),
        ),
    ]
