# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instance_manager', '0007_auto_20161020_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='location',
            field=models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, to='instance_manager.Location'),
        ),
    ]
